#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * @fileoverview Feature capture wizard.
 *
 * Interactive entry point that:
 *   1. Collects capture configuration via prompts.
 *   2. Validates production hostname policy.
 *   3. Scaffolds the .context-capture/<app>/<module>/<feature> tree.
 *   4. For each iteration, launches a headed browser with a checkpoint REPL.
 *   5. Optionally launches Playwright codegen after each iteration.
 *   6. Writes _feature-brief.md and _capture-manifest.json.
 */

const fs = require("fs");
const os = require("os");
const path = require("path");
const playwright = require("@playwright/test");

let prompts;
try {
  prompts = require("prompts");
} catch (error) {
  console.error("Missing dependency `prompts`. Run: npm install");
  process.exit(1);
}

const { classifyHostname } = require("./production-check");
const { captureIteration } = require("./capture-session");
const { runCodegen } = require("./codegen-runner");
const { DEFAULT_PATTERNS } = require("./redaction");

const DEFAULT_CAPTURE_ROOT = "playwright/.context-capture";
const TEMPLATES_DIR = path.resolve(__dirname, "templates");

function nowIsoCompact() {
  return new Date().toISOString();
}

function safeSegment(input, max = 60) {
  return String(input || "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, max);
}

async function ensureCaptureRoot(rootDir) {
  fs.mkdirSync(rootDir, { recursive: true });
  const gitignorePath = path.join(rootDir, ".gitignore");
  if (!fs.existsSync(gitignorePath)) {
    const content = [
      "# Auto-generated by scripts/capture/wizard.js",
      "# Captured artifacts contain sanitized DOM data — keep them local by default.",
      "*",
      "!.gitignore",
      "!**/_feature-brief.md",
      "",
    ].join("\n");
    fs.writeFileSync(gitignorePath, content, "utf8");
  }
}

async function collectAnswers() {
  const onCancel = () => {
    console.log("Capture cancelled.");
    process.exit(0);
  };

  const baseAnswers = await prompts(
    [
      {
        type: "text",
        name: "captureRoot",
        message: "Capture root directory",
        initial: DEFAULT_CAPTURE_ROOT,
      },
      {
        type: "text",
        name: "app",
        message: "Application name (kebab-case)",
        validate: (value) => (safeSegment(value) ? true : "Provide a valid name"),
      },
      {
        type: "text",
        name: "moduleName",
        message: "Module name (kebab-case)",
        validate: (value) => (safeSegment(value) ? true : "Provide a valid module"),
      },
      {
        type: "text",
        name: "featureKey",
        message: "Feature key (kebab-case, e.g. book-appointment)",
        validate: (value) => (safeSegment(value) ? true : "Provide a feature key"),
      },
      {
        type: "text",
        name: "featureTitle",
        message: "Human-readable feature title",
        initial: (prev) => (prev || "").replace(/-/g, " "),
      },
      {
        type: "text",
        name: "startUrl",
        message: "Starting URL for this feature",
        validate: (value) => {
          try {
            // eslint-disable-next-line no-new
            new URL(value);
            return true;
          } catch (error) {
            return "Provide a valid URL";
          }
        },
      },
      {
        type: "text",
        name: "testIdAttribute",
        message: "Test-id attribute used by the app",
        initial: "data-testid",
      },
      {
        type: "select",
        name: "authMode",
        message: "Authentication mode",
        choices: [
          { title: "Use existing storageState file", value: "storage" },
          { title: "Public page — no auth required", value: "none" },
        ],
        initial: 0,
      },
      {
        type: (prev) => (prev === "storage" ? "text" : null),
        name: "storageStatePath",
        message: "Path to storageState JSON",
        initial: "playwright/.auth/user.json",
        validate: (value) =>
          fs.existsSync(value) ? true : `File not found: ${value}`,
      },
      {
        type: "number",
        name: "iterationCount",
        message: "How many input variations / iterations to capture?",
        initial: 1,
        min: 1,
        max: 20,
      },
    ],
    { onCancel },
  );

  const iterations = [];
  for (let i = 0; i < baseAnswers.iterationCount; i += 1) {
    const itAnswers = await prompts(
      [
        {
          type: "text",
          name: "key",
          message: `Variation ${i + 1} key`,
          validate: (value) => (safeSegment(value) ? true : "Provide a key"),
        },
        {
          type: "text",
          name: "description",
          message: `Variation ${i + 1} description`,
        },
      ],
      { onCancel },
    );
    iterations.push({
      key: safeSegment(itAnswers.key),
      description: itAnswers.description || "",
    });
  }

  const redactionAnswers = await prompts(
    [
      {
        type: "list",
        name: "customPatterns",
        message: "Custom redaction regex patterns (comma-separated, optional)",
        separator: ",",
      },
      {
        type: "list",
        name: "hiddenSelectors",
        message: "Selectors to exclude entirely from capture (comma-separated, optional)",
        separator: ",",
      },
      {
        type: "confirm",
        name: "wantCodegen",
        message: "Run Playwright codegen after each iteration?",
        initial: false,
      },
      {
        type: "confirm",
        name: "wantHar",
        message: "Record network HAR alongside DOM capture? (enables api-layer replay in tests)",
        initial: false,
      },
      {
        type: (prev) => (prev ? "text" : null),
        name: "harUrlPattern",
        message: "URL glob pattern for HAR recording (e.g. **/api/**)",
        initial: "**/api/**",
      },
      {
        type: "text",
        name: "freeFormNotes",
        message: "Free-form notes for the AI (special instructions, edge cases)",
        initial: "",
      },
    ],
    { onCancel },
  );

  return {
    ...baseAnswers,
    iterations,
    customPatterns: (redactionAnswers.customPatterns || []).filter((entry) => String(entry).trim()),
    hiddenSelectors: (redactionAnswers.hiddenSelectors || []).filter((entry) => String(entry).trim()),
    wantCodegen: Boolean(redactionAnswers.wantCodegen),
    wantHar: Boolean(redactionAnswers.wantHar),
    harUrlPattern: redactionAnswers.harUrlPattern || "**/api/**",
    freeFormNotes: redactionAnswers.freeFormNotes || "",
  };
}

async function confirmProductionPolicy(startUrl) {
  const verdict = classifyHostname(startUrl);
  if (verdict.level === "invalid") {
    console.error("Invalid URL provided.");
    process.exit(1);
  }
  if (verdict.level === "hard") {
    console.error("");
    console.error(`✗ Refusing to capture against ${verdict.hostname}`);
    console.error(`  Reason: ${verdict.reason}`);
    console.error("  Re-run with `ALLOW_PRODUCTION=1` env var to override (audit only).");
    if (process.env.ALLOW_PRODUCTION !== "1") {
      process.exit(2);
    }
    console.error("  ALLOW_PRODUCTION=1 detected — proceeding under explicit override.");
  }
  if (verdict.level === "soft") {
    const { proceed } = await prompts({
      type: "confirm",
      name: "proceed",
      message: `Hostname '${verdict.hostname}' looks production-like. Continue?`,
      initial: false,
    });
    if (!proceed) {
      console.log("Capture cancelled.");
      process.exit(0);
    }
  }
}

function renderTemplate(template, replacements) {
  return Object.entries(replacements).reduce(
    (acc, [key, value]) => acc.split(`{{${key}}}`).join(value),
    template,
  );
}

function buildIterationTable(iterations, results) {
  const lines = ["| # | Key | Description | States |", "|---|-----|-------------|--------|"];
  iterations.forEach((iter, idx) => {
    const result = results[idx] || { states: [] };
    const seq = String(idx + 1).padStart(2, "0");
    lines.push(
      `| ${seq} | ${iter.key} | ${iter.description || "(no description)"} | ${result.states.length} |`,
    );
  });
  return lines.join("\n");
}

async function main() {
  console.log("");
  console.log("Feature Capture Wizard");
  console.log("======================");
  console.log("");

  const answers = await collectAnswers();
  await confirmProductionPolicy(answers.startUrl);

  const captureRoot = path.resolve(answers.captureRoot);
  await ensureCaptureRoot(captureRoot);

  const featureDir = path.join(
    captureRoot,
    safeSegment(answers.app),
    safeSegment(answers.moduleName),
    safeSegment(answers.featureKey),
  );
  fs.mkdirSync(featureDir, { recursive: true });

  console.log("");
  console.log(`Output directory: ${path.relative(process.cwd(), featureDir).replace(/\\/g, "/")}`);
  console.log("");

  const results = [];

  for (let i = 0; i < answers.iterations.length; i += 1) {
    const iteration = answers.iterations[i];
    const seq = String(i + 1).padStart(2, "0");
    const iterationDir = path.join(featureDir, `${seq}-${iteration.key}`);

    const result = await captureIteration({
      iteration,
      iterationDir,
      startUrl: answers.startUrl,
      storageState: answers.authMode === "storage" ? answers.storageStatePath : null,
      testIdAttribute: answers.testIdAttribute,
      hiddenSelectors: answers.hiddenSelectors,
      customRedactionPatterns: answers.customPatterns,
      harRecording: answers.wantHar
        ? {
            urlPattern: answers.harUrlPattern,
            outputPath: path.join(iterationDir, "_network.har"),
          }
        : null,
      playwright,
    });

    if (result.aborted) {
      console.log("Capture aborted by user.");
      break;
    }

    let codegenScriptPath = null;
    if (answers.wantCodegen) {
      const outFile = path.join(iterationDir, "_codegen-script.spec.ts");
      try {
        const codegenResult = await runCodegen({
          startUrl: answers.startUrl,
          storageState: answers.authMode === "storage" ? answers.storageStatePath : null,
          outputFile: outFile,
          customRedactionPatterns: answers.customPatterns,
          testIdAttribute: answers.testIdAttribute,
        });
        if (codegenResult.recorded) {
          codegenScriptPath = path
            .relative(process.cwd(), codegenResult.file)
            .replace(/\\/g, "/");
        }
      } catch (error) {
        console.log(`  Codegen skipped: ${error.message}`);
      }
    }

    results.push({ ...result, codegenScriptPath });
  }

  const briefPath = path.join(featureDir, "_feature-brief.md");
  const manifestPath = path.join(featureDir, "_capture-manifest.json");

  const manifest = {
    schemaVersion: "1.0",
    capturedAt: nowIsoCompact(),
    capturedBy: os.userInfo().username || "unknown",
    feature: {
      app: safeSegment(answers.app),
      module: safeSegment(answers.moduleName),
      key: safeSegment(answers.featureKey),
      startUrl: answers.startUrl,
      testIdAttribute: answers.testIdAttribute,
      storageState: answers.authMode === "storage" ? answers.storageStatePath : null,
    },
    iterations: answers.iterations.map((iter, idx) => ({
      key: iter.key,
      description: iter.description,
      states: (results[idx] && results[idx].states) || [],
      codegenScript: (results[idx] && results[idx].codegenScriptPath) || null,
      networkHar: answers.wantHar
        ? path
            .relative(
              process.cwd(),
              path.join(
                featureDir,
                `${String(idx + 1).padStart(2, "0")}-${iter.key}`,
                "_network.har",
              ),
            )
            .replace(/\\/g, "/")
        : null,
    })),
    redaction: {
      defaultPatterns: Object.keys(DEFAULT_PATTERNS),
      customPatterns: answers.customPatterns,
      hiddenSelectors: answers.hiddenSelectors,
    },
    freeFormNotes: answers.freeFormNotes,
  };

  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), "utf8");

  const template = fs.readFileSync(path.join(TEMPLATES_DIR, "feature-brief.md.tmpl"), "utf8");
  const brief = renderTemplate(template, {
    FEATURE_TITLE: answers.featureTitle || answers.featureKey,
    APP: manifest.feature.app,
    MODULE: manifest.feature.module,
    FEATURE_KEY: manifest.feature.key,
    CAPTURED_AT: manifest.capturedAt,
    CAPTURED_BY: manifest.capturedBy,
    START_URL: manifest.feature.startUrl,
    STORAGE_STATE: manifest.feature.storageState || "(none)",
    ITERATION_TABLE: buildIterationTable(answers.iterations, results),
    DEFAULT_PATTERNS: manifest.redaction.defaultPatterns.join(", "),
    CUSTOM_PATTERNS: manifest.redaction.customPatterns.length
      ? manifest.redaction.customPatterns.join(", ")
      : "(none)",
    HIDDEN_SELECTORS: manifest.redaction.hiddenSelectors.length
      ? manifest.redaction.hiddenSelectors.join(", ")
      : "(none)",
    FREE_FORM_NOTES: answers.freeFormNotes || "(none)",
    BRIEF_PATH: path.relative(process.cwd(), briefPath).replace(/\\/g, "/"),
  });
  fs.writeFileSync(briefPath, brief, "utf8");

  console.log("");
  console.log("✓ Capture complete");
  console.log(`  Brief:    ${path.relative(process.cwd(), briefPath).replace(/\\/g, "/")}`);
  console.log(`  Manifest: ${path.relative(process.cwd(), manifestPath).replace(/\\/g, "/")}`);
  console.log("");
}

main().catch((error) => {
  console.error("Capture failed:");
  console.error(error);
  process.exit(1);
});
