/**
 * @fileoverview Example module API config.
 * Demonstrates createModuleConfig with standard CRUD + one custom endpoint.
 *
 * Config keys generated by the factory:
 *   EXAMPLE_CONFIG.EXAMPLES_LIST     GET    /api/v1/examples?*
 *   EXAMPLE_CONFIG.EXAMPLES_DETAILS  GET    /api/v1/examples/*
 *   EXAMPLE_CONFIG.EXAMPLES_CREATE   POST   /api/v1/examples
 *   EXAMPLE_CONFIG.EXAMPLES_UPDATE   PUT    /api/v1/examples/*
 *   EXAMPLE_CONFIG.EXAMPLES_DELETE   DELETE /api/v1/examples/*
 *   EXAMPLE_CONFIG.EXAMPLE_SEARCH    POST   /api/v1/examples/search
 */

import { createModuleConfig } from "@core/api";

export const EXAMPLE_CONFIG = createModuleConfig({
  basePath: "/api/v1",
  prefix: "example",
  resources: {
    examples: ["LIST", "DETAILS", "CREATE", "UPDATE", "DELETE"],
  },
  custom: {
    EXAMPLE_SEARCH: {
      alias: "exampleSearchExamples",
      method: "POST",
      endpoint: "/api/v1/examples/search",
    },
  },
});
